from __future__ import annotations

from datetime import date
from pathlib import Path

import pandas as pd

from trading.backtest.metrics import BacktestMetrics


def _fmt_pct(x: float | None) -> str:
    if x is None:
        return "—"
    return f"{x * 100:.2f}%"


def _fmt_num(x: float | None) -> str:
    if x is None:
        return "—"
    return f"{x:.2f}"


def _columns_block(
    label: str,
    series: list[tuple[str, BacktestMetrics | None]],
) -> list[str]:
    headers = ["Metric"] + [name for name, _ in series]
    rows = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]

    def line(label_: str, getter, fmt) -> str:
        vals = [fmt(getter(m)) if m is not None else "—" for _, m in series]
        return "| " + " | ".join([label_, *vals]) + " |"

    rows.append(line("Total return", lambda m: m.total_return, _fmt_pct))
    rows.append(line("CAGR", lambda m: m.cagr, _fmt_pct))
    rows.append(line("Annualised vol", lambda m: m.vol, _fmt_pct))
    rows.append(line("Sharpe (rf=0)", lambda m: m.sharpe, _fmt_num))
    rows.append(line("Max drawdown", lambda m: m.max_drawdown, _fmt_pct))
    rows.append(line("Monthly win rate", lambda m: m.monthly_win_rate, _fmt_pct))
    rows.append(line("Trading days", lambda m: float(m.n_days), lambda x: str(int(x))))
    rows.append(line("Months", lambda m: float(m.n_months), lambda x: str(int(x))))
    return rows


def _annual_table(annual: pd.DataFrame, label: str) -> list[str]:
    if annual.empty:
        return [f"_{label}: no data._", ""]
    out = [f"### {label}", "", "| Year | Return | Sharpe | MDD | Best mo. | Worst mo. | Days |"]
    out.append("|---|---:|---:|---:|---:|---:|---:|")
    for year, row in annual.iterrows():
        out.append(
            f"| {year} | {_fmt_pct(row['return'])} | {_fmt_num(row['sharpe'])} | "
            f"{_fmt_pct(row['max_drawdown'])} | {_fmt_pct(row['best_month'])} | "
            f"{_fmt_pct(row['worst_month'])} | {int(row['n_days'])} |"
        )
    out.append("")
    return out


def _trade_stats_block(trades: pd.DataFrame) -> list[str]:
    if trades is None or trades.empty:
        return []
    n = len(trades)
    wins = (trades["pnl_pct"] > 0).sum()
    win_rate = wins / n
    avg_pnl = trades["pnl_pct"].mean()
    avg_win = trades.loc[trades["pnl_pct"] > 0, "pnl_pct"].mean() if wins else 0.0
    avg_loss = trades.loc[trades["pnl_pct"] <= 0, "pnl_pct"].mean() if n - wins else 0.0
    avg_hold = trades["holding_days"].mean()
    by_reason = trades["exit_reason"].value_counts().to_dict()

    out = [
        "## Trade summary",
        "",
        f"- **Trades**: {n}",
        f"- **Win rate**: {win_rate * 100:.1f}% ({wins}/{n})",
        f"- **Avg P&L per trade**: {avg_pnl * 100:.2f}%",
        f"- **Avg win**: {avg_win * 100:.2f}%   **Avg loss**: {avg_loss * 100:.2f}%",
        f"- **Avg holding days**: {avg_hold:.1f}",
        f"- **Exit reasons**: "
        + ", ".join(f"{k}={v}" for k, v in sorted(by_reason.items())),
        "",
    ]
    return out


def render(
    strategy: str,
    gross: BacktestMetrics,
    net: BacktestMetrics,
    benchmark: BacktestMetrics | None,
    config: dict,
    annual_net: pd.DataFrame,
    annual_benchmark: pd.DataFrame | None,
    avg_turnover: float,
    total_cost: float,
    trades: pd.DataFrame | None = None,
) -> str:
    lines = [
        f"# Backtest — {strategy}",
        "",
        f"Generated by `trading` v0.1 on {date.today().isoformat()}.",
        "",
        "## Configuration",
        "",
    ]
    for k, v in config.items():
        lines.append(f"- **{k}**: {v}")

    lines += [
        "",
        "## Headline results",
        "",
    ]
    series: list[tuple[str, BacktestMetrics | None]] = [
        ("Strategy (gross)", gross),
        ("Strategy (net)", net),
    ]
    if benchmark is not None:
        series.append(("Benchmark", benchmark))
    lines += _columns_block(strategy, series)

    lines += [
        "",
        "## Cost summary",
        "",
        f"- **Avg turnover per rebalance**: {avg_turnover * 100:.1f}% (sum of |Δweight|)"
        if avg_turnover > 0 else "- **Turnover**: not applicable (per-asset signals)",
        f"- **Total cost drag over period**: {total_cost * 100:.2f}% of capital",
        "",
    ]
    lines += _trade_stats_block(trades) if trades is not None else []
    lines += [
        "## Annual breakdown",
        "",
    ]
    lines += _annual_table(annual_net, "Strategy (net)")
    if annual_benchmark is not None:
        lines += _annual_table(annual_benchmark, "Benchmark")

    lines += [
        "## Caveats",
        "",
        "- **Survivorship bias**: universe is current Nifty 50 names; delisted/dropped names absent.",
        "- **Costs are a flat bps approximation**, not a precise broker-fee model. Includes brokerage, STT, exchange and stamp duty (~10–25 bps round-trip is realistic for Indian retail equities).",
        "- **No slippage on illiquid names** — Nifty 50 is generally fine; revisit if universe expands.",
        "- **No stops/targets** — pure monthly rebalance of top-N. The live recommender adds ATR stops which the backtest does not model.",
        "",
    ]
    return "\n".join(lines) + "\n"


def write_report(text: str, reports_dir: Path, slug: str) -> Path:
    reports_dir.mkdir(parents=True, exist_ok=True)
    path = reports_dir / f"backtest_{slug}_{date.today().isoformat()}.md"
    path.write_text(text)
    return path
