from __future__ import annotations

from datetime import date
from pathlib import Path
from textwrap import dedent

from trading.decision.recommend import Recommendation


def render(recommendations: list[Recommendation], as_of: date | None = None) -> str:
    as_of = as_of or date.today()
    if not recommendations:
        return f"# Recommendations — {as_of.isoformat()}\n\nNo recommendations generated.\n"

    header = dedent(
        f"""\
        # Recommendations — {as_of.isoformat()}

        Generated by `trading` v0.1. Paper-trade only — verify before any execution.

        | # | Ticker | Dir | Entry | Stop | Target | Shares | Notional ₹ | Risk ₹ | Conv | Score |
        |---|--------|-----|------:|-----:|-------:|-------:|-----------:|-------:|:----:|------:|
        """
    )
    rows = []
    for i, r in enumerate(recommendations, start=1):
        rows.append(
            f"| {i} | {r.ticker} | {r.direction} | "
            f"{r.entry:.2f} | {r.stop:.2f} | {r.target:.2f} | "
            f"{r.shares} | {r.notional:,.0f} | {r.risk_inr:,.0f} | "
            f"{'★' * r.conviction} | {r.score * 100:.1f}% |"
        )
    table = header + "\n".join(rows) + "\n"

    details = ["\n## Rationale\n"]
    for i, r in enumerate(recommendations, start=1):
        details.append(f"**{i}. {r.ticker}** — {r.rationale}\n")
    details.append("\n---\n*Not investment advice. v1 single-signal output (12-1 momentum).*\n")

    return table + "\n".join(details)


def write_report(text: str, reports_dir: Path, as_of: date | None = None) -> Path:
    as_of = as_of or date.today()
    reports_dir.mkdir(parents=True, exist_ok=True)
    path = reports_dir / f"{as_of.isoformat()}.md"
    path.write_text(text, encoding="utf-8")
    return path
