from __future__ import annotations

from datetime import date
from pathlib import Path
from textwrap import dedent

from trading.decision.recommend import Recommendation

_SIGNAL_NOTE = {
    "momentum": "12-1 cross-sectional momentum (long leaders, optional short laggards)",
    "mean_rev": "RSI mean-reversion (oversold pullbacks long / overbought bounces short)",
}


def render(
    recommendations: list[Recommendation],
    as_of: date | None = None,
    strategy: str = "momentum",
) -> str:
    as_of = as_of or date.today()
    title = f"# Recommendations ({strategy}) — {as_of.isoformat()}"
    if not recommendations:
        return f"{title}\n\nNo recommendations generated.\n"

    n_long = sum(1 for r in recommendations if r.direction == "LONG")
    n_short = sum(1 for r in recommendations if r.direction == "SHORT")
    header = dedent(
        f"""\
        {title}

        Generated by `trading` v0.1. Paper-trade only — verify before any execution.
        {n_long} long / {n_short} short.

        | # | Ticker | Dir | Entry | Stop | Target | Shares | Notional ₹ | Risk ₹ | Conv | Score |
        |---|--------|-----|------:|-----:|-------:|-------:|-----------:|-------:|:----:|------:|
        """
    )
    rows = []
    for i, r in enumerate(recommendations, start=1):
        rows.append(
            f"| {i} | {r.ticker} | {r.direction} | "
            f"{r.entry:.2f} | {r.stop:.2f} | {r.target:.2f} | "
            f"{r.shares} | {r.notional:,.0f} | {r.risk_inr:,.0f} | "
            f"{'★' * r.conviction} | {r.score * 100:.1f}% |"
        )
    table = header + "\n".join(rows) + "\n"

    details = ["\n## Rationale\n"]
    for i, r in enumerate(recommendations, start=1):
        details.append(f"**{i}. {r.ticker}** — {r.rationale}\n")
    note = _SIGNAL_NOTE.get(strategy, strategy)
    details.append(f"\n---\n*Not investment advice. Signal: {note}.*\n")

    return table + "\n".join(details)


def write_report(text: str, reports_dir: Path, as_of: date | None = None) -> Path:
    as_of = as_of or date.today()
    reports_dir.mkdir(parents=True, exist_ok=True)
    path = reports_dir / f"{as_of.isoformat()}.md"
    path.write_text(text, encoding="utf-8")
    return path
